name: Scrape files

on:
  push:
    branches:
      - master
      - main

jobs:
  scrape-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: valitydev/action-download-file@v1
        with:
          url: https://aktv.top/live.txt
          target-path: ./scrape-files/data/aktv-top-live.txt